/**
 * Daily Coding Log — content generator
 *
 * This script runs inside GitHub Actions and generates today's daily log:
 *   - Picks a random coding challenge from challenges/*.json
 *   - Picks a random tip from data/tips.json
 *   - Generates a markdown file at logs/YYYY-MM-DD.md
 *   - Updates README.md with today's snapshot
 *
 * The Action then commits and pushes the changes.
 */

import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const LOGS_DIR = path.join(ROOT, "logs");
const CHALLENGES_DIR = path.join(ROOT, "challenges");
const TIPS_FILE = path.join(ROOT, "data", "tips.json");
const README_FILE = path.join(ROOT, "README.md");

// ---------- Helpers ----------
const pick = (arr) => arr[Math.floor(Math.random() * arr.length)];

const today = () => {
  const d = new Date();
  return d.toISOString().slice(0, 10); // YYYY-MM-DD
};

const dayNumber = (startDate = "2026-06-29") => {
  const start = new Date(startDate + "T00:00:00Z").getTime();
  const now = Date.now();
  return Math.floor((now - start) / (1000 * 60 * 60 * 24)) + 1;
};

const formatDate = (dateStr) => {
  const d = new Date(dateStr + "T00:00:00");
  return d.toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });
};

// ---------- Load data ----------
const loadChallenges = () => {
  const files = fs.readdirSync(CHALLENGES_DIR).filter((f) => f.endsWith(".json"));
  return files.flatMap((file) => {
    const content = fs.readFileSync(path.join(CHALLENGES_DIR, file), "utf-8");
    return JSON.parse(content);
  });
};

const loadTips = () => {
  if (!fs.existsSync(TIPS_FILE)) return [];
  return JSON.parse(fs.readFileSync(TIPS_FILE, "utf-8"));
};

// ---------- Generate today's log ----------
const generateDailyLog = () => {
  const dateStr = today();
  const day = dayNumber();
  const challenges = loadChallenges();
  const tips = loadTips();

  if (challenges.length === 0) {
    console.error("No challenges found in challenges/ directory");
    process.exit(1);
  }

  const challenge = pick(challenges);
  const tip = tips.length > 0 ? pick(tips) : null;

  const markdown = `# Day ${day} · ${formatDate(dateStr)}

> Auto-generated by GitHub Actions. Random pick from a curated pool of ${challenges.length} challenges and ${tips.length} tips.

---

## 🧠 Challenge of the Day

### ${challenge.title}

**Difficulty:** ${challenge.difficulty}
**Topic:** ${challenge.topic}

**Problem:**

${challenge.problem}

${challenge.example ? `**Example:**

\`\`\`
${challenge.example}
\`\`\`

` : ""}**Hint:**

${challenge.hint}

<details>
<summary>🔍 Reveal solution</summary>

\`\`\`${challenge.solutionLang || "javascript"}
${challenge.solution}
\`\`\`

${challenge.explanation ? `**Explanation:** ${challenge.explanation}` : ""}

</details>

---

## 💡 Tip of the Day

${tip ? `**${tip.title}**

${tip.body}` : "_No tips available yet._"}

---

## 🎯 Today's Reflection

- [ ] I attempted the challenge before looking at the solution
- [ ] I learned something new from the tip
- [ ] I worked on a portfolio project today
- [ ] I read at least one page of official docs

**What I learned today:**

_Today I focused on..._

**Tomorrow I want to explore:**

_Next I want to look into..._

---

## 📚 Currently Building

Working through a 14-day portfolio build plan. Today is **Day ${day}**.

| Day | Project | Status |
|-----|---------|--------|
| 1 | Calculator App, Notes App, Realtime Chat | ✅ Done |
| 2 | Weather App | ${day >= 2 ? "✅ Done" : "⏳ In progress"} |
| 3 | Todo List with Drag & Drop | ${day >= 3 ? "✅ Done" : "⏳ Pending"} |
| 4 | Movie Explorer | ${day >= 4 ? "✅ Done" : "⏳ Pending"} |
| 5 | Pomodoro Timer + Stats | ${day >= 5 ? "✅ Done" : "⏳ Pending"} |
| 6 | GitHub User Search | ${day >= 6 ? "✅ Done" : "⏳ Pending"} |
| 7 | React Todo (Vite) | ${day >= 7 ? "✅ Done" : "⏳ Pending"} |
| 8 | URL Shortener API | ${day >= 8 ? "✅ Done" : "⏳ Pending"} |
| 9 | Markdown Blog | ${day >= 9 ? "✅ Done" : "⏳ Pending"} |
| 10 | Expense Tracker | ${day >= 10 ? "✅ Done" : "⏳ Pending"} |
| 11 | Real-time Whiteboard | ${day >= 11 ? "✅ Done" : "⏳ Pending"} |
| 12 | JWT Auth Demo | ${day >= 12 ? "✅ Done" : "⏳ Pending"} |
| 13 | AI Chatbot UI | ${day >= 13 ? "✅ Done" : "⏳ Pending"} |
| 14 | Portfolio Dashboard | ${day >= 14 ? "✅ Done" : "⏳ Pending"} |

---

_Hit me with a PR if you spot a bug or have a better solution — happy to learn from you!_ 🙌
`;

  // Ensure logs dir exists
  fs.mkdirSync(LOGS_DIR, { recursive: true });
  fs.writeFileSync(path.join(LOGS_DIR, `${dateStr}.md`), markdown);
  console.log(`✅ Generated logs/${dateStr}.md`);

  return { dateStr, day, challenge, tip };
};

// ---------- Update README ----------
const updateReadme = ({ dateStr, day, challenge, tip }) => {
  const readme = `# 📓 Daily Coding Log

> A new coding challenge, tip, and reflection prompt — auto-committed every day by GitHub Actions.

![Daily Commit](https://github.com/arjundroid12/daily-coding-log/actions/workflows/daily.yml/badge.svg)
![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)
![Day](https://img.shields.io/badge/day-${day}-blue)

## 📅 Today — ${formatDate(dateStr)} (Day ${day})

### 🧠 Challenge: ${challenge.title}
**${challenge.difficulty}** · ${challenge.topic}

${challenge.problem.split("\n")[0]}

👉 [Full challenge + solution](./logs/${dateStr}.md)

### 💡 Tip: ${tip ? tip.title : "—"}
${tip ? tip.body.split("\n")[0] : ""}

---

## 🗂️ Archive

All daily logs are saved in [\`./logs/\`](./logs/) as \`YYYY-MM-DD.md\` files.

${generateArchiveList()}

---

## ⚙️ How It Works

1. **GitHub Action** (\`.github/workflows/daily.yml\`) runs on a schedule (multiple times daily, commits at random times between 9 AM - 10 PM IST)
2. **\`scripts/generate-daily.mjs\`** picks a random challenge and tip, generates today's markdown log, and updates this README
3. The Action commits and pushes the changes — green square unlocked for today ✅

## 📚 Challenge Pool

Challenges live in [\`./challenges/\`](./challenges/) as JSON files. Want to add more? Open a PR!

| File | Topic | Count |
|------|-------|-------|
${generateChallengeTable()}

## 💡 Tips Pool

Tips live in [\`./data/tips.json\`](./data/tips.json).

## 🤝 Contributing

Found a bug in a solution? Have a better approach? Want to add a challenge?
PRs are welcome — that's how we all learn!

## 📄 License

MIT © Arjun Vashishtha
`;

  fs.writeFileSync(README_FILE, readme);
  console.log(`✅ Updated README.md`);
};

// ---------- Helpers for README ----------
const generateArchiveList = () => {
  if (!fs.existsSync(LOGS_DIR)) return "_No logs yet._";
  const files = fs
    .readdirSync(LOGS_DIR)
    .filter((f) => f.endsWith(".md"))
    .sort()
    .reverse()
    .slice(0, 14); // last 14 days
  if (files.length === 0) return "_No logs yet._";
  return files.map((f) => `- [${f.replace(".md", "")}](./logs/${f})`).join("\n");
};

const generateChallengeTable = () => {
  if (!fs.existsSync(CHALLENGES_DIR)) return "_No challenges yet._";
  const files = fs.readdirSync(CHALLENGES_DIR).filter((f) => f.endsWith(".json"));
  return files
    .map((f) => {
      const content = JSON.parse(fs.readFileSync(path.join(CHALLENGES_DIR, f), "utf-8"));
      const topic = content[0]?.topic || "—";
      return `| [\`challenges/${f}\`](./challenges/${f}) | ${topic} | ${content.length} |`;
    })
    .join("\n");
};

// ---------- Main ----------
console.log(`🚀 Generating daily log for ${today()} (Day ${dayNumber()})`);
const result = generateDailyLog();
updateReadme(result);
console.log("🎉 Done.");
